# Generated by Django 3.2.10 on 2022-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemunerationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billid', models.CharField(max_length=10)),
                ('Name_Of_Exam', models.CharField(max_length=100)),
                ('Name_Of_Sub', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('01', 'CIV'), ('02', 'MECH'), ('03', 'EEE'), ('04', 'ECE'), ('05', 'CSE'), ('06', 'AI&ML'), ('07', 'CAD')], max_length=10)),
                ('Name_Of_Staff', models.CharField(max_length=200)),
                ('MobileNum', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Others', 'Others')], max_length=40)),
                ('Name_of_College', models.CharField(max_length=50)),
                ('Name_of_Bank', models.CharField(max_length=100)),
                ('Bank_Location', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('acc_num', models.CharField(max_length=50)),
                ('paper_setting_num', models.IntegerField(blank=True, null=True)),
                ('paper_setting_rate', models.IntegerField(blank=True, null=True)),
                ('paper_valuation_num', models.IntegerField(blank=True, null=True)),
                ('paper_valuation_rate', models.IntegerField(blank=True, null=True)),
                ('chief_examiner_num', models.IntegerField(blank=True, null=True)),
                ('chief_examiner_rate', models.IntegerField(blank=True, null=True)),
                ('lab_examiner_num', models.IntegerField(blank=True, null=True)),
                ('lab_examiner_rate', models.IntegerField(blank=True, null=True)),
                ('viva_rate', models.IntegerField(blank=True, null=True)),
                ('da_days', models.IntegerField(blank=True, null=True)),
                ('da_rate', models.IntegerField(blank=True, null=True)),
                ('ta_days', models.IntegerField(blank=True, null=True)),
                ('ta_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
