# Generated by Django 3.2.10 on 2022-04-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsection', '0003_auto_20220326_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billid', models.CharField(max_length=10)),
                ('Name_Of_Exam', models.CharField(max_length=100)),
                ('Name_Of_Sub', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CIV', 'CIV'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('AI&ML', 'AI&ML'), ('CAD', 'CAD')], max_length=10)),
                ('Name_Of_Staff', models.CharField(max_length=200)),
                ('MobileNum', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Others', 'Others')], max_length=40)),
                ('Name_of_College', models.CharField(max_length=50)),
                ('Name_of_Bank', models.CharField(max_length=100)),
                ('Bank_Location', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('acc_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RemunerationForm',
        ),
        migrations.CreateModel(
            name='RemunerationDetails',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examsection.staffdetails')),
                ('nature_of_work', models.CharField(choices=[('Question Paper Setting', 'Question Paper Setting'), ('Paper Valuation', 'Paper Valuation'), ('Chief Examiner', 'Chief Examiner'), ('Lab Examiner', 'Lab Examiner'), ('Thesis Viva Voce', 'Thesis Viva Voce')], max_length=30)),
                ('number_of_papers', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('da_days', models.IntegerField(blank=True, default=0)),
                ('da_rate', models.IntegerField(blank=True, default=0)),
                ('ta_days', models.IntegerField(blank=True, default=0)),
                ('ta_rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
