# Generated by Django 3.2.10 on 2022-04-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsection', '0004_auto_20220407_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Sr. Assistant Professor', 'Sr. Assistant Professor'), ('Professor', 'Professor'), ('Others', 'Others')], max_length=40),
        ),
    ]
